### ISSUE TITLE
Problem with using this build

### ISSUE THREAD

**Issue by hiqsol** [lucasw/ros_from_src#15]
Thanks to you I could build the ROS on Ubuntu 22.04 on RPi CM4.

But, unfortunately, I failed to use it to build my ROS project.

What I did:
1. `source ros_from_src/build/ros/setup.bash`
2. `mkdir ~/catkin_ws` and download there my project
3. `cd ~/catkin_ws`
4. `catkin_make`

But I get errors with simplest dependency:
Could not find a package configuration file provided by "std_msgs" 

![image](https://user-images.githubusercontent.com/11820365/209333497-716dc90c-b584-4378-a505-333050e68d10.png)

As far as I can see `std_msgs` is cloned and built inside this project but it is not available somehow.

What am I doing wrong? How can I use the ROS built with this project?

Thank you!

**Comment by lucasw** [comment]
Do you have libstd-msgs-dev, python3-std-msgs, & ros-std-msgs installed (through normal apt), `apt install ros-*` from the readme should have gotten them for you. 

Does `/usr/share/std_msgs/msg` exist on your system?  And do you have any of these:

```
libstd-msgs-dev: /usr/share/pkgconfig/std_msgs.pc
libstd-msgs-dev: /usr/share/std_msgs/cmake/std_msgs-msg-extras.cmake
libstd-msgs-dev: /usr/share/std_msgs/cmake/std_msgs-msg-paths.cmake
libstd-msgs-dev: /usr/share/std_msgs/cmake/std_msgsConfig-version.cmake
libstd-msgs-dev: /usr/share/std_msgs/cmake/std_msgsConfig.cmake
```

**Comment by hiqsol** [comment]
Yes I have those files installed.
But it was not enough.

What helped me was that I've sourced `ros_from_source/build/catkin_ws/devel/setup.bash`
