### ISSUE TITLE
rviz Ogre error

### ISSUE THREAD

**Issue by gorghino** [lucasw/ros_from_src#23]
Hi @lucasw 
I compiled noetic on PopOS! 22.04 LTS with your scripts (Thanks!).
I'm getting the following error when I open rviz.

`[ERROR] [1652828623.528481534 /system_rviz_lucasw_XPS_8940_716577_8729550478975508344 ${shortfile}:58]: Error: ScriptCompiler - unexpected token in ogre1.9.fontdef(1): 'Liberation'. If this is a legacy script you must prepend the type (e.g. font, overlay).`

I saw you mentioned in https://github.com/lucasw/ros_from_src/issues/6 but I don't see how I can fix it.

```
gorgo@pop-os:~/catkin_ws$ glxinfo | grep OpenGL
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA GeForce RTX 2080 Super with Max-Q Design/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 525.105.17
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6.0 NVIDIA 525.105.17
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 525.105.17
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```

**Comment by lucasw** [comment]
Sorry I missed this earlier- that wasn't really an error according to https://github.com/ros-visualization/rviz/issues/1508#issuecomment-636399914 and I've been using rviz fine despite seeing that every time I run it- but it is good to not have 'normal errors' so this deletes the old fontdef file https://github.com/lucasw/rviz/commit/aa16e4b738e5d987bd03232568c66ffbf70449e8
